var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/empreiteiro/faq/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__673376f3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_85a99bb7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__43558541._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__ace3d42a._.js")
R.c("server/chunks/ssr/app_not-found_tsx_339d4b53._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_empreiteiro_layout_tsx_c6cf24d3._.js")
R.c("server/chunks/ssr/_next-internal_server_app_empreiteiro_faq_page_actions_b20dd1c7.js")
R.m(804492)
module.exports=R.m(804492).exports
