// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/acesso-plataforma/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/acesso-plataforma">> = Specific
  const handler = {} as typeof import("../../app/acesso-plataforma/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/anuncios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/anuncios">> = Specific
  const handler = {} as typeof import("../../app/admin/anuncios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/auditoria/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/auditoria">> = Specific
  const handler = {} as typeof import("../../app/admin/auditoria/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/caixa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/caixa">> = Specific
  const handler = {} as typeof import("../../app/admin/caixa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/clientes/[id]/obras/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clientes/[id]/obras">> = Specific
  const handler = {} as typeof import("../../app/admin/clientes/[id]/obras/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/clientes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clientes/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/clientes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clientes">> = Specific
  const handler = {} as typeof import("../../app/admin/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/configuracoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/configuracoes">> = Specific
  const handler = {} as typeof import("../../app/admin/configuracoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/disputas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/disputas">> = Specific
  const handler = {} as typeof import("../../app/admin/disputas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/empreiteiras/[id]/obras/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/empreiteiras/[id]/obras">> = Specific
  const handler = {} as typeof import("../../app/admin/empreiteiras/[id]/obras/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/empreiteiras/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/empreiteiras/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/empreiteiras/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/empreiteiras/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/empreiteiras">> = Specific
  const handler = {} as typeof import("../../app/admin/empreiteiras/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/entradas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/entradas">> = Specific
  const handler = {} as typeof import("../../app/admin/entradas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/faq">> = Specific
  const handler = {} as typeof import("../../app/admin/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/financeiro/obras/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/financeiro/obras/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/financeiro/obras/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/financeiro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/financeiro">> = Specific
  const handler = {} as typeof import("../../app/admin/financeiro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/obras/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/obras/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/obras/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/obras/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/obras">> = Specific
  const handler = {} as typeof import("../../app/admin/obras/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/planos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/planos">> = Specific
  const handler = {} as typeof import("../../app/admin/planos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/saidas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/saidas">> = Specific
  const handler = {} as typeof import("../../app/admin/saidas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/oauth-success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/oauth-success">> = Specific
  const handler = {} as typeof import("../../app/auth/oauth-success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cadastro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cadastro">> = Specific
  const handler = {} as typeof import("../../app/cadastro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contratante/atividades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contratante/atividades">> = Specific
  const handler = {} as typeof import("../../app/contratante/atividades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contratante/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contratante/chat">> = Specific
  const handler = {} as typeof import("../../app/contratante/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contratante/configuracoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contratante/configuracoes">> = Specific
  const handler = {} as typeof import("../../app/contratante/configuracoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contratante/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contratante/dashboard">> = Specific
  const handler = {} as typeof import("../../app/contratante/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contratante/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contratante/faq">> = Specific
  const handler = {} as typeof import("../../app/contratante/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contratante/medicoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contratante/medicoes">> = Specific
  const handler = {} as typeof import("../../app/contratante/medicoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contratante/minhas-obras/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contratante/minhas-obras/[id]">> = Specific
  const handler = {} as typeof import("../../app/contratante/minhas-obras/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contratante/minhas-obras/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contratante/minhas-obras">> = Specific
  const handler = {} as typeof import("../../app/contratante/minhas-obras/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contratante/notificacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contratante/notificacoes">> = Specific
  const handler = {} as typeof import("../../app/contratante/notificacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contratante/nova-obra/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contratante/nova-obra">> = Specific
  const handler = {} as typeof import("../../app/contratante/nova-obra/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contratante/pagamentos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contratante/pagamentos">> = Specific
  const handler = {} as typeof import("../../app/contratante/pagamentos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contratante/planos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contratante/planos">> = Specific
  const handler = {} as typeof import("../../app/contratante/planos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empreiteiro/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empreiteiro/chat">> = Specific
  const handler = {} as typeof import("../../app/empreiteiro/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empreiteiro/configuracoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empreiteiro/configuracoes">> = Specific
  const handler = {} as typeof import("../../app/empreiteiro/configuracoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empreiteiro/dashboard/atividades-recentes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empreiteiro/dashboard/atividades-recentes">> = Specific
  const handler = {} as typeof import("../../app/empreiteiro/dashboard/atividades-recentes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empreiteiro/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empreiteiro/dashboard">> = Specific
  const handler = {} as typeof import("../../app/empreiteiro/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empreiteiro/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empreiteiro/faq">> = Specific
  const handler = {} as typeof import("../../app/empreiteiro/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empreiteiro/minhas-obras/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empreiteiro/minhas-obras/[id]">> = Specific
  const handler = {} as typeof import("../../app/empreiteiro/minhas-obras/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empreiteiro/minhas-obras/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empreiteiro/minhas-obras">> = Specific
  const handler = {} as typeof import("../../app/empreiteiro/minhas-obras/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empreiteiro/notificacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empreiteiro/notificacoes">> = Specific
  const handler = {} as typeof import("../../app/empreiteiro/notificacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empreiteiro/novas-obras/[id]/aplicar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empreiteiro/novas-obras/[id]/aplicar">> = Specific
  const handler = {} as typeof import("../../app/empreiteiro/novas-obras/[id]/aplicar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empreiteiro/novas-obras/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empreiteiro/novas-obras/[id]">> = Specific
  const handler = {} as typeof import("../../app/empreiteiro/novas-obras/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empreiteiro/novas-obras/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empreiteiro/novas-obras">> = Specific
  const handler = {} as typeof import("../../app/empreiteiro/novas-obras/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empreiteiro/obras-salvas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empreiteiro/obras-salvas">> = Specific
  const handler = {} as typeof import("../../app/empreiteiro/obras-salvas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empreiteiro/pagamentos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empreiteiro/pagamentos">> = Specific
  const handler = {} as typeof import("../../app/empreiteiro/pagamentos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empreiteiro/planos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empreiteiro/planos">> = Specific
  const handler = {} as typeof import("../../app/empreiteiro/planos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/politica-privacidade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/politica-privacidade">> = Specific
  const handler = {} as typeof import("../../app/politica-privacidade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recuperar-senha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recuperar-senha">> = Specific
  const handler = {} as typeof import("../../app/recuperar-senha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reset-senha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-senha">> = Specific
  const handler = {} as typeof import("../../app/reset-senha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/termos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/termos">> = Specific
  const handler = {} as typeof import("../../app/termos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verificar-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verificar-email">> = Specific
  const handler = {} as typeof import("../../app/verificar-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/xgestao-inteligente/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/xgestao-inteligente">> = Specific
  const handler = {} as typeof import("../../app/xgestao-inteligente/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/clientes/[id]/aprovacao/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/clientes/[id]/aprovacao">> = Specific
  const handler = {} as typeof import("../../app/api/admin/clientes/[id]/aprovacao/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/empreiteiras/[id]/aprovacao/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/empreiteiras/[id]/aprovacao">> = Specific
  const handler = {} as typeof import("../../app/api/admin/empreiteiras/[id]/aprovacao/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/oauth-convert/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/oauth-convert">> = Specific
  const handler = {} as typeof import("../../app/api/auth/oauth-convert/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/refresh">> = Specific
  const handler = {} as typeof import("../../app/api/auth/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/resend-verification/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/resend-verification">> = Specific
  const handler = {} as typeof import("../../app/api/auth/resend-verification/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/verify-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-email">> = Specific
  const handler = {} as typeof import("../../app/api/auth/verify-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clientes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clientes/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/clientes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clientes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clientes">> = Specific
  const handler = {} as typeof import("../../app/api/clientes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contratante/chat/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contratante/chat/conversations">> = Specific
  const handler = {} as typeof import("../../app/api/contratante/chat/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contratante/chat/messages/[conversationId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contratante/chat/messages/[conversationId]">> = Specific
  const handler = {} as typeof import("../../app/api/contratante/chat/messages/[conversationId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contratante/faq/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contratante/faq">> = Specific
  const handler = {} as typeof import("../../app/api/contratante/faq/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contratante/minhas-obras/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contratante/minhas-obras/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/contratante/minhas-obras/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contratante/minhas-obras/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contratante/minhas-obras">> = Specific
  const handler = {} as typeof import("../../app/api/contratante/minhas-obras/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contratante/pagamentos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contratante/pagamentos">> = Specific
  const handler = {} as typeof import("../../app/api/contratante/pagamentos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dashboard/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/stats">> = Specific
  const handler = {} as typeof import("../../app/api/dashboard/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empreiteiras/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empreiteiras/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/empreiteiras/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empreiteiras/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empreiteiras">> = Specific
  const handler = {} as typeof import("../../app/api/empreiteiras/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empreiteiro/candidaturas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empreiteiro/candidaturas">> = Specific
  const handler = {} as typeof import("../../app/api/empreiteiro/candidaturas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/financeiro/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/financeiro">> = Specific
  const handler = {} as typeof import("../../app/api/financeiro/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/marketplace-leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketplace-leads">> = Specific
  const handler = {} as typeof import("../../app/api/marketplace-leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/obras/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/obras/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/obras/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/obras/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/obras">> = Specific
  const handler = {} as typeof import("../../app/api/obras/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/perfil/contratante/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/perfil/contratante">> = Specific
  const handler = {} as typeof import("../../app/api/perfil/contratante/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/perfil/empreiteiro/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/perfil/empreiteiro">> = Specific
  const handler = {} as typeof import("../../app/api/perfil/empreiteiro/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/test/emails/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test/emails">> = Specific
  const handler = {} as typeof import("../../app/api/test/emails/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/test/login-as/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test/login-as">> = Specific
  const handler = {} as typeof import("../../app/api/test/login-as/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/test/oauth-simulate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test/oauth-simulate">> = Specific
  const handler = {} as typeof import("../../app/api/test/oauth-simulate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cadastro/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/cadastro">> = Specific
  const handler = {} as typeof import("../../app/cadastro/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contratante/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contratante">> = Specific
  const handler = {} as typeof import("../../app/contratante/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empreiteiro/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/empreiteiro">> = Specific
  const handler = {} as typeof import("../../app/empreiteiro/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/politica-privacidade/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/politica-privacidade">> = Specific
  const handler = {} as typeof import("../../app/politica-privacidade/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/termos/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/termos">> = Specific
  const handler = {} as typeof import("../../app/termos/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/xgestao-inteligente/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/xgestao-inteligente">> = Specific
  const handler = {} as typeof import("../../app/xgestao-inteligente/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
