var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/contratante/configuracoes/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__f5c6626e._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_76471610._.js")
R.c("server/chunks/ssr/[root-of-the-server]__43558541._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__ace3d42a._.js")
R.c("server/chunks/ssr/app_not-found_tsx_339d4b53._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_contratante_layout_tsx_fd055688._.js")
R.c("server/chunks/ssr/_next-internal_server_app_contratante_configuracoes_page_actions_2ffd997c.js")
R.m(338559)
module.exports=R.m(338559).exports
