var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/xgestao-inteligente/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__2ce4ba2d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_c4ddb4f4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__43558541._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__ace3d42a._.js")
R.c("server/chunks/ssr/app_not-found_tsx_339d4b53._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_xgestao-inteligente_layout_tsx_5d3b221d._.js")
R.c("server/chunks/ssr/_next-internal_server_app_xgestao-inteligente_page_actions_0c0268f8.js")
R.m(141459)
module.exports=R.m(141459).exports
