var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/usuarios/route.js")
R.c("server/chunks/_09z_9mh._.js")
R.c("server/chunks/[root-of-the-server]__1_djlgo._.js")
R.c("server/chunks/node_modules_next_19ifh39._.js")
R.c("server/chunks/node_modules_drizzle-orm_14wyhk7._.js")
R.c("server/chunks/node_modules_zod_v3_1zi-s0x._.js")
R.c("server/chunks/node_modules_entities_lib_esm_1wz4ktz._.js")
R.c("server/chunks/[root-of-the-server]__0igkyok._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_usuarios_route_actions_1x02jw7.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/admin/usuarios/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/admin/usuarios/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
