var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/logout/route.js")
R.c("server/chunks/_0-twcmo._.js")
R.c("server/chunks/[root-of-the-server]__1aesdgf._.js")
R.c("server/chunks/node_modules_next_0vyac-5._.js")
R.c("server/chunks/node_modules_drizzle-orm_10211j8._.js")
R.c("server/chunks/node_modules_zod_v3_1zi-s0x._.js")
R.c("server/chunks/[root-of-the-server]__1tozo14._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_logout_route_actions_0regwyr.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/auth/logout/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/auth/logout/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
