var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/register/route.js")
R.c("server/chunks/_09pc8vt._.js")
R.c("server/chunks/[root-of-the-server]__0-4een1._.js")
R.c("server/chunks/node_modules_next_042i93j._.js")
R.c("server/chunks/node_modules_drizzle-orm_1jb8u6e._.js")
R.c("server/chunks/node_modules_zod_v3_1zi-s0x._.js")
R.c("server/chunks/node_modules_entities_lib_esm_1wz4ktz._.js")
R.c("server/chunks/[root-of-the-server]__0c4ga3d._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_register_route_actions_0g4vfdr.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/auth/register/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/auth/register/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
