var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/test/login-as/route.js")
R.c("server/chunks/_f3bf4d58._.js")
R.c("server/chunks/[root-of-the-server]__be741f03._.js")
R.c("server/chunks/node_modules_next_b166b5d5._.js")
R.c("server/chunks/node_modules_drizzle-orm_bdb2784c._.js")
R.c("server/chunks/node_modules_zod_lib_index_mjs_db18e9a4._.js")
R.c("server/chunks/[root-of-the-server]__a8409cea._.js")
R.c("server/chunks/_next-internal_server_app_api_test_login-as_route_actions_5a64a7c4.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/test/login-as/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/test/login-as/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
