var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/planos/route.js")
R.c("server/chunks/_192nnb1._.js")
R.c("server/chunks/[root-of-the-server]__0m-60nu._.js")
R.c("server/chunks/node_modules_next_1ms22cd._.js")
R.c("server/chunks/node_modules_drizzle-orm_10211j8._.js")
R.c("server/chunks/node_modules_zod_v3_1zi-s0x._.js")
R.c("server/chunks/[root-of-the-server]__1dav0ep._.js")
R.c("server/chunks/_next-internal_server_app_api_planos_route_actions_1sbpqir.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/planos/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/planos/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
