var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/reset-senha/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0721d873._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_0ed751f5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__43558541._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__ace3d42a._.js")
R.c("server/chunks/ssr/app_not-found_tsx_339d4b53._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_reset-senha_page_actions_01f36e79.js")
R.m(748857)
module.exports=R.m(748857).exports
